---

- name: Run vagrant development environment
  hosts: all
  become: true
  user: vagrant
  vars:
    - fqdn: elk.local
    - user: vagrant
  roles:
    - common
    - elasticsearch
    - kibana
    - logstash
    - nginx
