---

- name: Update apt cache
  apt: update_cache=yes

- name: Install latest packages
  apt: name={{ item }} state=latest
  with_items:
    - python
    - openssl
    - openjdk-8-jre
  tags:
    - base
